# Generated by Django 4.0.3 on 2023-05-25 07:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0005_answer_voter_question_voter_alter_answer_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='question',
            name='voter',
        ),
        migrations.AddField(
            model_name='answer',
            name='dislike_voter',
            field=models.ManyToManyField(related_name='dislike_voter_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='like_voter',
            field=models.ManyToManyField(related_name='like_voter_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='dislike_voter',
            field=models.ManyToManyField(related_name='dislike_voter_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='like_voter',
            field=models.ManyToManyField(related_name='like_voter_question', to=settings.AUTH_USER_MODEL),
        ),
    ]
